services:
  - type: web
    name: mini-crm-full-r3
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_DIR
        value: /data
      - key: JWT_SECRET
        value: change-me
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        value: admin123
      - key: ALLOWED_ORIGIN
        value: "*"
      - key: RATE_LIMIT_WINDOW_MIN
        value: "1"
      - key: RATE_LIMIT_MAX
        value: "120"
      - key: BACKUP_CRON
        value: "0 17 * * *"
    disk:
      name: crm-data
      mountPath: /data
      sizeGB: 5
    healthCheckPath: /health
